In [ ]:
#Machine learnig

In [ ]:
#1)Introduction to NumPy

In [2]:
#2).Arrays in python
#creating arrays using:
#np.array()
from numpy import *
arr=array([1,2,3,4,5])
print(arr.dtype)
print(arr)

int32
[1 2 3 4 5]


In [8]:
#np.zeros()
from numpy import *
arr=zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [9]:
#np.ones()
from numpy import *
arr=ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [10]:
#np.arange() (steps involve)
from numpy import *
arr=arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [11]:
#np.linspace() (partition)
from numpy import *
arr=linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [12]:
#a).Array indexing 
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
print(arr)

[25 45 64 78 89 77 46 25 49]


In [13]:
print(arr[0])

25


In [15]:
arr=np.array([[25,45,64],[78,89,77],[46,25,49]])
print(arr)

[[25 45 64]
 [78 89 77]
 [46 25 49]]


In [16]:
print(arr[0,0])

25


In [18]:
print(arr[2,0])

46


In [20]:
#b).Array slicing
arr=np.array([25,45,64,78,89,77,46,25,49])
print(arr[0:5])

[25 45 64 78 89]


In [8]:
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
print(arr[2:7:2])  #(slicing with step2)

[64 89 46]


In [7]:
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
print(arr[::])

[25 45 64 78 89 77 46 25 49]


In [27]:
print(arr[::-1])

[49 25 46 77 89 78 64 45 25]


In [28]:
arr=np.array([[25,45,64],[78,89,77],[46,25,49]])
print(arr)

[[25 45 64]
 [78 89 77]
 [46 25 49]]


In [35]:
print(arr[:,2])

[64 77 49]


In [38]:
print(arr[1:3,0:2])

[[78 89]
 [46 25]]


In [35]:
#3)Array operations
#a).arithmetic operations
#addition
import numpy as np
arr1=np.array([25,45,64,78,89,77,46,25,49])
arr2=np.array([10,28,40,39,27,56,20,79,89])
add=arr+arr2
print(add)


[ 35  73 104 117 116 133  66 104 138]


In [10]:
#substraction
import numpy as np
arr1=np.array([25,45,64,78,89,77,46,25,49])
arr2=np.array([10,28,40,39,27,56,20,79,89])
sub=arr1-arr2
print(sub)


[ 15  17  24  39  62  21  26 -54 -40]


In [14]:
#multipliction
import numpy as np
arr1=np.array([[25,45,64],[78,89,77],[46,25,49]])
arr2=np.array([[10,28,40],[39,27,56],[20,79,89]])
mult=arr1@arr2
print(mult)

[[ 3285  6971  9216]
 [ 5791 10670 14957]
 [ 2415  5834  7601]]


In [31]:
#division
import numpy as np
arr1=np.array([25,45,64,78,89,77,46,25,49])
arr2=np.array([10,28,40,39,27,56,20,79,89])
div=arr1/arr2
print(div)

[2.5        1.60714286 1.6        2.         3.2962963  1.375
 2.3        0.3164557  0.5505618 ]


In [15]:
#b).broadcasting
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [17]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([[1],[2],[3]])
print(arr1)
print(arr2)
print()
print(arr1+arr2)

[1 2 3]
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [18]:
#c).element wise operations and functions
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)

[ 6  8 10 12]


In [21]:
#4).Array shapes and Reshaping
#a)chaking array dimentions
#shape
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([[1],[2],[3]])
print(arr1.shape)
print(arr2.shape)

(3,)
(3, 1)


In [9]:
#ndim
import numpy as np
arr1=np.array([[[25,45,64],[78,89,77]],[[46,25,49],[46,78,99]]])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([7,8,9])
print(arr1)
print(arr1.ndim)
print()
print(arr2)
print(arr2.ndim)
print()
print(arr3)
print(arr3.ndim)

[[[25 45 64]
  [78 89 77]]

 [[46 25 49]
  [46 78 99]]]
3

[[1 2 3]
 [4 5 6]]
2

[7 8 9]
1


In [25]:
#b)changing array shape with 
#reshape()
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([[1],[2],[3],[4]])
print(arr1.reshape(2,2))
print(arr2.reshape(2,2))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
#flatten()
import numpy as np
arr1=np.array([[25,45,64],[78,89,77],[46,25,49]])
arr2=np.array([[10,28,40],[39,27,56],[20,79,89]])
f1=arr1.flatten()
f2=arr2.flatten()
print(arr1)
print(f1)
print()
print(arr2)
print(f2)


[[25 45 64]
 [78 89 77]
 [46 25 49]]
[25 45 64 78 89 77 46 25 49]

[[10 28 40]
 [39 27 56]
 [20 79 89]]
[10 28 40 39 27 56 20 79 89]


In [13]:
#transpose()
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([[1],[2],[3]])
t1=np.transpose(arr1)
t2=np.transpose(arr2)
print(arr1)
print(arr1.shape)
print(t1)
print(t1.shape)
print()
print(arr2)
print(arr2.shape)
print(t2)
print(t2.shape)


[1 2 3]
(3,)
[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]
(1, 3)


In [15]:
#c)concatenating and spliting array using
#np.concatenate()
import numpy as np
arr1=np.array([[25,45,64],[78,89,77],[46,25,49]])
arr2=np.array([[10,28,40],[39,27,56],[20,79,89]])
c=np.concatenate((arr1,arr2),axis=0)
print(arr1)
print()
print(arr2)
print()
print(c)

[[25 45 64]
 [78 89 77]
 [46 25 49]]

[[10 28 40]
 [39 27 56]
 [20 79 89]]

[[25 45 64]
 [78 89 77]
 [46 25 49]
 [10 28 40]
 [39 27 56]
 [20 79 89]]


In [16]:
arr1=np.array([[25,45,64],[78,89,77],[46,25,49]])
arr2=np.array([[10,28,40],[39,27,56],[20,79,89]])
c=np.concatenate((arr1,arr2),axis=1)
print(arr1)
print()
print(arr2)
print()
print(c)

[[25 45 64]
 [78 89 77]
 [46 25 49]]

[[10 28 40]
 [39 27 56]
 [20 79 89]]

[[25 45 64 10 28 40]
 [78 89 77 39 27 56]
 [46 25 49 20 79 89]]


In [20]:
#np.split()
import numpy as np
arr1=np.array([25,45,64,78,89,77,46,25,49])
arr2=np.array([10,28,40,39,27,56,20,79,89])
s1=np.split(arr1,3)
s2=np.split(arr2,3)
print(arr1)
print(s1)
print()
print(arr2)
print(s2)

[25 45 64 78 89 77 46 25 49]
[array([25, 45, 64]), array([78, 89, 77]), array([46, 25, 49])]

[10 28 40 39 27 56 20 79 89]
[array([10, 28, 40]), array([39, 27, 56]), array([20, 79, 89])]


In [25]:
#np.hstack()
import numpy as np
arr1=np.array([[25,45,64],[78,89,77],[46,25,49]])
arr2=np.array([[10,28,40],[39,27,56],[20,79,89]])
hs=np.hstack([arr1,arr2,arr1])
print(arr1)
print()
print(arr2)
print()
print(hs)

[[25 45 64]
 [78 89 77]
 [46 25 49]]

[[10 28 40]
 [39 27 56]
 [20 79 89]]

[[25 45 64 10 28 40 25 45 64]
 [78 89 77 39 27 56 78 89 77]
 [46 25 49 20 79 89 46 25 49]]


In [27]:
#np.vstack()
import numpy as np
arr1=np.array([[25,45,64],[78,89,77],[46,25,49]])
arr2=np.array([[10,28,40],[39,27,56],[20,79,89]])
vs=np.vstack([arr1,arr2,arr1])
print(arr1)
print()
print(arr2)
print()
print(vs)

[[25 45 64]
 [78 89 77]
 [46 25 49]]

[[10 28 40]
 [39 27 56]
 [20 79 89]]

[[25 45 64]
 [78 89 77]
 [46 25 49]
 [10 28 40]
 [39 27 56]
 [20 79 89]
 [25 45 64]
 [78 89 77]
 [46 25 49]]


In [28]:
#5)Arry Manipulation
#a).indexing and slicing
#.Array indexing 
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
print(arr)

[25 45 64 78 89 77 46 25 49]


In [29]:
#b).Array slicing
arr=np.array([25,45,64,78,89,77,46,25,49])
print(arr[0:5])

[25 45 64 78 89]


In [3]:
#b).masking
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
mask=arr%2==0
arr[mask]=-1
print(arr)


[25 45 -1 -1 89 77 -1 25 49]


In [33]:
#c).fancy indexing
import numpy as np
arr1=np.array([[25,45,64],[78,89,77],[46,25,49],[50,99,26]])
print(arr1)
print()
print(arr1[[2,0,3]])


[[25 45 64]
 [78 89 77]
 [46 25 49]
 [50 99 26]]

[[46 25 49]
 [25 45 64]
 [50 99 26]]


In [37]:
#6).Mathematical functions
#a).universal functions(ufuncs):
#np.add()
import numpy as np
arr1=np.array([25,45,64,78,89,77,46,25,49])
arr2=np.array([10,28,40,39,27,56,20,79,89])
add=arr1+arr2
print(add)


[ 35  73 104 117 116 133  66 104 138]


In [36]:
#np.subtract()
import numpy as np
arr1=np.array([25,45,64,78,89,77,46,25,49])
arr2=np.array([10,28,40,39,27,56,20,79,89])
sub=arr1-arr2
print(sub)


[ 15  17  24  39  62  21  26 -54 -40]


In [40]:
#np.multiply()
import numpy as np
arr1=np.array([[25,45,64],[78,89,77],[46,25,49]])
arr2=np.array([[10,28,40],[39,27,56],[20,79,89]])
mul=arr1@arr2
print(arr1)
print()
print(arr2)
print()
print(mul)


[[25 45 64]
 [78 89 77]
 [46 25 49]]

[[10 28 40]
 [39 27 56]
 [20 79 89]]

[[ 3285  6971  9216]
 [ 5791 10670 14957]
 [ 2415  5834  7601]]


In [5]:
#b)statistical functions:
#np.mean()
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
y=np.mean(x)
print(y)

55.333333333333336


In [6]:
#np.median()
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
y=np.median(x)
print(y)

49.0


In [7]:
#np.std()
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
y=np.std(x)
print(y)

21.77154105707724


In [8]:
#np.var()
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
y=np.var(x)
print(y)

474.0


In [9]:
#np.min()
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
y=np.min(x)
print(y)

25


In [10]:
#np.max()
import numpy as np
arr=np.array([25,45,64,78,89,77,46,25,49])
y=np.max(x)
print(y)

89


In [3]:
#c).linear algebra functions:
#np.dot()
import numpy as np
x=np.array([25,45,64,78,89,77,46,25,49])
y=np.array([10,28,40,39,27,56,20,79,89])
z=np.dot((x),(y))
print(z)

21083


In [5]:
#np.matmul()
import numpy as np
x=np.array([25,45,64,78,89,77,46,25,49])
y=np.array([10,28,40,39,27,56,20,79,89])
print(x@y)

21083


In [6]:
#np.linalg.inv()
import numpy as np
x=np.array([[25,45,64],[78,89,77],[46,25,49]])
x_inv= np.linalg.inv(x)
print(x_inv)

[[-0.02739664  0.00680417  0.0250911 ]
 [ 0.00314904  0.01933285 -0.03449323]
 [ 0.02411265 -0.01625129  0.01445184]]


In [10]:
#np.linalg.eig()
import numpy as np
x=np.array([[1,2,3],[3,4,5],[6,7,8]])
y=np.array([10,28,40,39,27,56,20,79,89])
[eig_vec,eig_val] = np.linalg.eig(x)
print(x)
print()
print(eig_val)
print()
print(eig_vec)

[[1 2 3]
 [3 4 5]
 [6 7 8]]

[[ 0.26564776  0.74442863  0.40824829]
 [ 0.49120712  0.19070122 -0.81649658]
 [ 0.82954616 -0.63988988  0.40824829]]

[ 1.40663730e+01 -1.06637298e+00 -1.08222200e-15]


In [39]:
#7).Random number geneation:
#a).generating random numbers
#np.random.rand()
import numpy as np
arr=np.random.random(10)
print(arr)

[0.18532822 0.10837689 0.21969749 0.97862378 0.81168315 0.17194101
 0.81622475 0.27407375 0.43170418 0.94002982]


In [25]:
#np.random.randint()
import numpy as np
arr = np.random.randint(10,20,(2,3))
print(arr)

[[11 10 18]
 [14 10 19]]


In [27]:
#b).seeding random number generation
#np.random.seed()
import numpy as np
np.random.seed(100)
arr=np.random.randint(10,20,(2,3))
print(arr)

[[18 18 13]
 [17 17 10]]


In [40]:
#c).sampling,shuffling,and permutation.
#sampling
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [35]:
#shuffling
import numpy as np
from numpy import random
arr=np.array([1,2,3])
random.shuffle(arr)
print(arr)

[3 2 1]


In [36]:
#permutation
import numpy as np
from numpy import random
arr=np.array([1,2,3])
random.permutation(arr)
print(arr)


[1 2 3]


In [ ]:
#8).Broadcasting
#understanding how NumPy handles operations between array of different shapes.

In [ ]:
#Rules of broadcasting